import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/auth_provider.dart';

class AppLocalizations {
  static const List<Map<String, String>> supportedLanguages = [
    {'code': 'en', 'name': 'English', 'native': 'English', 'script': 'Latin'},
    {'code': 'hi', 'name': 'Hindi', 'native': 'हिन्दी', 'script': 'Devanagari'},
    {'code': 'bn', 'name': 'Bengali', 'native': 'বাংলা', 'script': 'Bengali'},
    {'code': 'te', 'name': 'Telugu', 'native': 'తెలుగు', 'script': 'Telugu'},
    {'code': 'mr', 'name': 'Marathi', 'native': 'मराठी', 'script': 'Devanagari'},
    {'code': 'ta', 'name': 'Tamil', 'native': 'தமிழ்', 'script': 'Tamil'},
    {'code': 'ur', 'name': 'Urdu', 'native': 'اردو', 'script': 'Arabic-RTL'},
    {'code': 'gu', 'name': 'Gujarati', 'native': 'ગુજરાતી', 'script': 'Gujarati'},
    {'code': 'kn', 'name': 'Kannada', 'native': 'ಕನ್ನಡ', 'script': 'Kannada'},
    {'code': 'or', 'name': 'Odia', 'native': 'ଓଡ଼ିଆ', 'script': 'Odia'},
    {'code': 'ml', 'name': 'Malayalam', 'native': 'മലയാളം', 'script': 'Malayalam'},
    {'code': 'pa', 'name': 'Punjabi', 'native': 'ਪੰਜਾਬੀ', 'script': 'Gurmukhi'},
    {'code': 'as', 'name': 'Assamese', 'native': 'অসমীয়া', 'script': 'Bengali-Assamese'},
    {'code': 'mai', 'name': 'Maithili', 'native': 'मैथिली', 'script': 'Devanagari'},
    {'code': 'sat', 'name': 'Santali', 'native': 'ᱥᱟᱱᱛᱟᱲᱤ', 'script': 'Ol Chiki'},
    {'code': 'ks', 'name': 'Kashmiri', 'native': 'کٲشُر', 'script': 'Arabic-RTL'},
    {'code': 'ne', 'name': 'Nepali', 'native': 'नेपाली', 'script': 'Devanagari'},
    {'code': 'kok', 'name': 'Konkani', 'native': 'कोंकणी', 'script': 'Devanagari'},
    {'code': 'doi', 'name': 'Dogri', 'native': 'डोगरी', 'script': 'Devanagari'},
    {'code': 'sd', 'name': 'Sindhi', 'native': 'سنڌي', 'script': 'Arabic-RTL'},
    {'code': 'brx', 'name': 'Bodo', 'native': 'बड़ो', 'script': 'Devanagari'},
    {'code': 'sa', 'name': 'Sanskrit', 'native': 'संस्कृतम्', 'script': 'Devanagari'},
    {'code': 'mni', 'name': 'Manipuri', 'native': 'ꯃꯤꯇꯩꯂꯣꯟ', 'script': 'Meitei Mayek'},
    {'code': 'he', 'name': 'Hebrew', 'native': 'עברית', 'script': 'Hebrew-RTL'},
    {'code': 'ar', 'name': 'Arabic', 'native': 'العربية', 'script': 'Arabic-RTL'},
  ];

  static bool isRtlLanguage(String langCodeOrName) {
    final lower = langCodeOrName.toLowerCase().trim();
    return lower == 'ur' || lower == 'urdu' ||
           lower == 'he' || lower == 'hebrew' ||
           lower == 'ar' || lower == 'arabic' ||
           lower == 'ks' || lower == 'kashmiri' ||
           lower == 'sd' || lower == 'sindhi';
  }

  static String getLocaleCode(String langCodeOrName) {
    return _normalizeLangCode(langCodeOrName);
  }

  // DICTIONARY 1: App Keys
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'nav_home': 'Home',
      'nav_discover': 'Discover',
      'nav_create': 'Create',
      'nav_wishes': 'Wishes',
      'nav_me': 'Me',
      'app_title': 'Karma Grid',
      'app_tagline': 'Proof of Good',
      'app_hero_sub': 'Do good. Show the difference. Create verified impact.',
      'login_title': 'Access Your Karma Passport',
      'login_subtitle': 'Sign in securely with Google to record actions & earn Karma',
      'login_welcome_back': 'Welcome to Karma Grid',
      'login_create_account': 'Create your Account',
      'login_sub_welcome': 'Enter to record deeds, verify impact, and earn Karma',
      'login_sub_signup': 'Join the community of verified impact',
      'login_fullname': 'Full Name',
      'login_fullname_hint': 'Your name',
      'login_email_phone': 'Email or Phone',
      'login_password': 'Password',
      'login_confirm_password': 'Confirm Password',
      'login_forgot_password': 'Forgot password?',
      'login_btn': 'LOGIN',
      'login_btn_create': 'Create Account',
      'login_or': 'OR',
      'login_google_btn': 'Continue with Google',
      'login_already_have_acc': 'Already have an account? ',
      'login_dont_have_acc': 'Don\'t have an account? ',
      'login_signin_link': 'Sign In',
      'login_secured_by': 'Secured by Proof of Good Integrity Ledger',
      'dash_welcome': 'Welcome back',
      'dash_metrics': 'Ecosystem metrics',
      'dash_karma': 'Karma',
      'dash_impact': 'Impact',
      'dash_trust': 'Trust Score',
      'dash_action_do': 'DO GOOD',
      'dash_action_do_sub': 'Find a deed & prove impact',
      'dash_action_report': 'REPORT',
      'dash_action_report_sub': 'Report a local problem',
      'dash_action_wish': 'MAKE A WISH',
      'dash_action_wish_sub': 'Ask community for help',
      'dash_action_help_wish': 'HELP A WISH',
      'dash_action_help_wish_sub': 'Support someone in need',
      'dash_search_placeholder': '🔎 Search actions, problems, NGOs, schools, wishes...',
      'dash_talk_mic': '🎙️ Talk to Karma',
      'dash_talk_desc': 'Speak in your language to find actions or report problems',
      'dash_today_opps': '🇮🇳 Today\'s Action Opportunities',
      'dash_view_all': 'View All',
      'dash_flywheel_title': 'Unified Flywheel Hub',
      'dash_flywheel_sub': 'Explore Stories, Karma Graph & Collective Intelligence',
      'opp_plastic_title': 'Plastic Recovery & Segregation',
      'opp_plastic_desc': 'Collect & photograph 5 items of plastic waste. Verified 1.5x Multiplier today!',
      'opp_compost_title': 'Neighborhood Composting Drive',
      'opp_compost_desc': 'Clear organic waste near park and start community pit with before/after photos.',
      'unit_credits': 'Credits',
      'unit_verified': 'Verified',
      'unit_rating': 'Rating',
      'step_before': 'BEFORE 📸',
      'step_before_desc': 'Photograph starting condition',
      'step_action': 'DO / FIX ⚡',
      'step_action_desc': 'Complete the positive action',
      'step_after': 'AFTER 📸',
      'step_after_desc': 'Photograph the change',
      'step_verified': 'VERIFIED ✓',
      'step_verified_desc': 'Multi-layer proof verification',
      'step_impact': 'IMPACT 🌍',
      'step_impact_desc': 'Measurable positive change',
      'step_karma': 'KARMA ✨',
      'step_karma_desc': 'Recognition & digital passport record',
      'fb_button': 'Feedback',
      'fb_title': 'Help Us Improve Karma Grid',
      'fb_subtitle': 'Share feedback in under 10 seconds',
      'fb_good': '👍 Good',
      'fb_difficult': '👎 Difficult',
      'fb_bug': '🐛 Problem',
      'fb_idea': '💡 Idea',
      'fb_voice_note': '🎙️ Record Voice Feedback',
      'fb_text_hint': 'Tell us what happened or what could be better...',
      'fb_submit': 'Submit Feedback (10s)',
      'fb_thank_you': 'Thank you! Your feedback helps everyone.',
      'fb_tab_give': 'Give Feedback 💡',
      'fb_tab_ideas': 'Community Ideas 👥',
      'demo_badge': 'Example / Demo Story',
      'demo_banner_title': 'The Proof of Good Journey',
      'demo_banner_sub': 'Real change is proven through before-and-after evidence.',
      'safety_title': '🛡️ Trust & Safety Promise',
      'safety_desc': 'No crypto hype • No arbitrary daily caps • Real evidence verification • Direct-to-vendor wish support',
      'rep_gold': '👑 Gold Validator',
      'rep_silver': '🛡️ Silver Contributor',
      'rep_citizen': '🌱 Green Citizen',
      'me_passport': '🪪 Karma Passport',
      'me_passport_sub': 'Your complete record of verified real-world impact',
      'me_my_actions': '🌱 My Actions',
      'me_my_reports': '🔎 My Reports',
      'me_no_actions': 'No actions submitted yet. Tap + Create!',
      'me_no_reports': 'No problem reports submitted yet.',
      'me_lang_region': 'Language & Region',
      'me_interface_mode': 'Interface Mode',
      'me_logout': 'Logout',
      'me_metric_recog': 'Recognition earned',
      'me_metric_verified': 'Verified deeds',
      'me_metric_trust': 'Audited trust',
      'me_passport_record': 'Verified Identity & Integrity Record',
      'me_view_full_passport': 'View Complete Passport',
      'me_level_green': 'Level 1 Green Citizen',
      'create_heading': 'What would you like to contribute today?',
      'create_sub': 'Choose how you want to create real-world positive change:',
      'create_do_action': 'Do an Action',
      'create_do_action_sub': 'Take a positive deed from the taxonomy, capture Before/After photo evidence, and earn Karma.',
      'create_report_prob': 'Report a Problem',
      'create_report_prob_sub': 'Photograph a visible issue (garbage dump, broken pipe, injured animal) with GPS verification.',
      'create_make_wish': 'Make a Wish',
      'create_make_wish_sub': 'Ask the community or NGOs for assistance with education, medical tools, or essential needs.',
      'create_propose': 'Add an Action Proposal',
      'create_propose_sub': 'Propose a brand new leap-year action to be added to the global Karma taxonomy.',
      'create_suggest': 'Suggest an Improvement',
      'create_suggest_sub': 'Help improve Karma Grid by submitting an idea, reporting a bug, or sharing local usability feedback.',
      'create_badge_action': 'Earn +20 to +100 Karma',
      'create_badge_report': 'Earn +20 Karma & +10 Trust',
      'create_badge_wish': 'Community Supported',
      'create_badge_propose': 'Governance Consensus',
      'create_badge_suggest': 'App Improvement',
      'disc_tab_actions': '🌱 Actions',
      'disc_tab_problems': '🚨 Problems',
      'disc_tab_challenges': '🏆 Challenges',
      'disc_tab_orgs': '🤝 Organizations',
      'disc_tab_missions': '🇮🇳 Missions & AI',
      'disc_search_hint': 'Search actions, problems, organizations...',
      'disc_do_this': 'Do This',
      'disc_fix_earn': 'Fix & Earn',
      'disc_join': 'Join',
      'disc_no_problems': 'No unresolved problems in your area!',
      'disc_report_issue': 'Report a new issue',
      'chal_plastic_title': 'Global Plastic Recovery Drive 🌍',
      'chal_plastic_desc': 'Collect & photograph 5 items of plastic waste. 1.5x Multiplier today!',
      'chal_tree_title': 'Delhi Tree Nurture Drive 🌳',
      'chal_tree_desc': 'Water and mulch 3 young neighborhood saplings.',
      'chal_animal_title': 'Stray Animal Winter Aid 🐾',
      'chal_animal_desc': 'Set out clean water bowls and warm bedding for neighborhood strays.',
      'org_green_earth': 'Green Earth Foundation 🌍',
      'org_green_earth_cat': 'Environment & Forestry',
      'org_apex': 'Apex Academy 🏫',
      'org_apex_cat': 'Civic Education & Youth',
      'org_mcd': 'Municipal Corporation Delhi 🏛️',
      'org_mcd_cat': 'Civic Sanitation & Infrastructure',
      'org_verified_ngo': '🛡️ Verified NGO • 98% Trust',
      'org_verified_school': '🛡️ Verified School • 95% Trust',
      'org_verified_muni': '🛡️ Verified Authority • 92% Trust',
      'mission_india30_title': 'India 30 Mission Hub',
      'mission_india30_sub': 'National targets for clean water, waste recovery, and education',
      'mission_flywheel_title': 'Ecosystem Flywheel & AI Core',
      'mission_flywheel_sub': 'YouTube Stories, Karma Graph, and Collective Intelligence Query Engine',
      'wishes_title': '🌟 Wish Come True Hub',
      'wishes_waiting': 'wishes waiting for sponsors',
      'wishes_make_btn': 'Make a Wish 💫',
      'wishes_tab_my': '✨ My Wishes',
      'wishes_tab_help': '🌟 I Can Help',
      'wishes_tab_fulfilling': '❤️ Being Fulfilled',
      'wishes_tab_made_possible': '✅ Made Possible',
      'wishes_empty_my': 'You haven\'t submitted any wishes yet.',
      'wishes_empty_help': 'No wishes matching this category need help right now.',
      'wishes_empty_fulfilling': 'No wishes are currently receiving active sponsorship.',
      'wishes_empty_completed': 'No wishes have been fully completed in this category yet.',
      'wish_cat_all': 'All',
      'wish_sponsor_btn': 'Sponsor Wish',
      'settings_title': 'Settings',
      'settings_acc_voice': 'ACCESSIBILITY & VOICE',
      'settings_app_mode': 'App Interface Mode',
      'settings_voice_lang': 'Voice Language',
      'settings_voice_guidance': 'Voice Guidance',
      'settings_voice_guidance_sub': 'Hear button descriptions and cues on tap',
      'settings_general': 'GENERAL SETTINGS',
      'settings_theme': 'Theme Selection',
      'settings_biometric': 'Biometric Security',
      'settings_push_notif': 'Push Notifications',
      'settings_admin': 'Admin & Trust Center',
      'settings_admin_sub': 'Ecosystem oversight, verification queue & audit log',
      'settings_support': 'SUPPORT & COMPLIANCE',
      'settings_report_abuse': 'Report Abuse / Fake Submission',
      'settings_help_faq': 'Help & FAQ Center',
      'settings_about': 'About Proof of Good',
      'settings_logout': 'Logout Passport',
      'eco_hub_title': 'Ecosystem Flywheel Hub',
      'eco_loop_badge': 'THE 4-STEP ACTION LOOP',
      'eco_loop_sub': 'Every real-world improvement follows this 4-step lifecycle:',
      'proof_upload_title': 'Proof Upload Hub',
      'proof_select_files': 'Select Verification Files',
      'proof_desc': 'Attach raw photo, video, or audio logs. The AI algorithm will parse metadata, GPS timestamps, and pixels to calculate a confidence score.',
      'proof_photo_btn': 'Upload Photo Proof (JPEG/PNG)',
      'proof_video_btn': 'Upload Video Capture (MP4)',
      'proof_audio_btn': 'Upload Audio Witness Testimony (WAV)',
      'proof_confirm_btn': 'Confirm & Return',
      'talk_where_can_do': '🌱 Where can I do good?',
      'talk_report_garbage': '🔎 Report garbage / waste',
      'talk_how_wish': '✨ How to make a wish?',
      'talk_my_karma': '📊 What is my Karma?',
    },
    'hi': {
      'nav_home': 'होम',
      'nav_discover': 'खोजें',
      'nav_create': 'बनाएं',
      'nav_wishes': 'इच्छाएं',
      'nav_me': 'प्रोफ़ाइल',
      'app_title': 'कर्म ग्रिड',
      'app_tagline': 'अच्छाई का प्रमाण',
      'app_hero_sub': 'अच्छा करें। बदलाव दिखाएं। वास्तविक प्रभाव बनाएं।',
      'login_title': 'अपना कर्म पासपोर्ट एक्सेस करें',
      'login_subtitle': 'कर्म कमाने और कार्य दर्ज करने के लिए गूगल से साइन इन करें',
      'login_welcome_back': 'कर्म ग्रिड में स्वागत है',
      'login_create_account': 'अपना खाता बनाएं',
      'login_sub_welcome': 'कार्य दर्ज करने और कर्म कमाने के लिए प्रवेश करें',
      'login_sub_signup': 'सत्यापित प्रभाव के समुदाय में शामिल हों',
      'login_fullname': 'पूरा नाम',
      'login_fullname_hint': 'आपका नाम',
      'login_email_phone': 'ईमेल या फ़ोन',
      'login_password': 'पासवर्ड',
      'login_confirm_password': 'पासवर्ड की पुष्टि करें',
      'login_forgot_password': 'पासवर्ड भूल गए?',
      'login_btn': 'लॉग इन करें',
      'login_btn_create': 'खाता बनाएं',
      'login_or': 'या',
      'login_google_btn': 'Google के साथ जारी रखें',
      'login_already_have_acc': 'क्या आपके पास पहले से खाता है? ',
      'login_dont_have_acc': 'खाता नहीं है? ',
      'login_signin_link': 'साइन इन करें',
      'login_secured_by': 'प्रूफ ऑफ गुड लेजर द्वारा सुरक्षित',
      'dash_welcome': 'स्वागत है',
      'dash_metrics': 'पारिस्थितिकी तंत्र मेट्रिक्स',
      'dash_karma': 'कर्म',
      'dash_impact': 'प्रभाव',
      'dash_trust': 'विश्वास स्कोर',
      'dash_action_do': 'अच्छा काम करें',
      'dash_action_do_sub': 'एक काम खोजें और प्रभाव साबित करें',
      'dash_action_report': 'समस्या दर्ज करें',
      'dash_action_report_sub': 'स्थानीय समस्या की रिपोर्ट करें',
      'dash_action_wish': 'इच्छा बनाएं',
      'dash_action_wish_sub': 'समुदाय से मदद मांगें',
      'dash_action_help_wish': 'इच्छा में मदद करें',
      'dash_action_help_wish_sub': 'जरूरतमंद की मदद करें',
      'dash_search_placeholder': '🔎 कार्य, समस्याएं, एनजीओ, स्कूल या इच्छाएं खोजें...',
      'dash_talk_mic': '🎙️ कर्म से बात करें',
      'dash_talk_desc': 'अपनी भाषा में बोलें और कार्य खोजें या समस्या बताएं',
      'dash_today_opps': '🇮🇳 आज के कार्य के अवसर',
      'dash_view_all': 'सभी देखें',
      'dash_flywheel_title': 'एकीकृत फ्लाईव्हील हब',
      'dash_flywheel_sub': 'कहानियां, कर्म ग्राफ और सामूहिक बुद्धिमत्ता देखें',
      'opp_plastic_title': 'प्लास्टिक कचरा निष्कासन व पृथक्करण',
      'opp_plastic_desc': '5 प्लास्टिक वस्तुएं एकत्र करें और फोटो लें। आज 1.5x बोनस!',
      'opp_compost_title': 'सामुदायिक खाद अभियान',
      'opp_compost_desc': 'पार्क के पास जैविक कचरा साफ करें और खाद गड्ढा शुरू करें।',
      'unit_credits': 'क्रेडिट्स',
      'unit_verified': 'सत्यापित',
      'unit_rating': 'रेटिंग',
      'step_before': 'पहले 📸',
      'step_before_desc': 'शुरुआती स्थिति की तस्वीर लें',
      'step_action': 'कार्य / सुधार ⚡',
      'step_action_desc': 'सकारात्मक कार्य पूरा करें',
      'step_after': 'बाद में 📸',
      'step_after_desc': 'बदलाव की तस्वीर लें',
      'step_verified': 'सत्यापित ✓',
      'step_verified_desc': 'बहुस्तरीय प्रमाण सत्यापन',
      'step_impact': 'प्रभाव 🌍',
      'step_impact_desc': 'मापने योग्य सकारात्मक बदलाव',
      'step_karma': 'कर्म ✨',
      'step_karma_desc': 'डिजिटल पासपोर्ट में मान्यता',
      'fb_button': 'प्रतिक्रिया',
      'fb_title': 'कर्म ग्रिड को बेहतर बनाएं',
      'fb_subtitle': '10 सेकंड में अपनी प्रतिक्रिया दें',
      'fb_good': '👍 अच्छा',
      'fb_difficult': '👎 कठिन',
      'fb_bug': '🐛 समस्या',
      'fb_idea': '💡 सुझाव',
      'fb_voice_note': '🎙️ आवाज़ में फीडबैक रिकॉर्ड करें',
      'fb_text_hint': 'बताएं कि क्या बेहतर किया जा सकता है...',
      'fb_submit': 'प्रतिक्रिया भेजें',
      'fb_thank_you': 'धन्यवाद! आपकी राय से सभी को मदद मिलेगी।',
      'fb_tab_give': 'फीडबैक दें 💡',
      'fb_tab_ideas': 'समुदायिक विचार 👥',
      'demo_badge': 'उदाहरण / डेमो कहानी',
      'demo_banner_title': 'प्रमाण कैसे काम करता है',
      'demo_banner_sub': 'वास्तविक बदलाव पहले और बाद के प्रमाण से साबित होता है।',
      'safety_title': '🛡️ विश्वास और सुरक्षा का वादा',
      'safety_desc': 'कोई भ्रामक दावा नहीं • वास्तविक प्रमाण सत्यापन • सुरक्षित इच्छा पूर्ति',
      'rep_gold': '👑 स्वर्ण सत्यापनकर्ता',
      'rep_silver': '🛡️ रजत योगदानकर्ता',
      'rep_citizen': '🌱 हरित नागरिक',
      'me_passport': '🪪 कर्म पासपोर्ट',
      'me_passport_sub': 'आपके सत्यापित वास्तविक प्रभाव का पूरा रिकॉर्ड',
      'me_my_actions': '🌱 मेरे कार्य',
      'me_my_reports': '🔎 मेरी रिपोर्ट',
      'me_no_actions': 'अभी तक कोई कार्य नहीं। + बनाएं पर टैप करें!',
      'me_no_reports': 'अभी तक कोई समस्या रिपोर्ट नहीं की गई।',
      'me_lang_region': 'भाषा और क्षेत्र',
      'me_interface_mode': 'इंटरफ़ेस मोड',
      'me_logout': 'लॉग आउट',
      'me_metric_recog': 'अर्जित मान्यता',
      'me_metric_verified': 'सत्यापित कार्य',
      'me_metric_trust': 'ऑडिटेड विश्वास',
      'me_passport_record': 'सत्यापित पहचान एवं सत्यनिष्ठा रिकॉर्ड',
      'me_view_full_passport': 'पूरा पासपोर्ट देखें',
      'me_level_green': 'स्तर 1 हरित नागरिक',
      'create_heading': 'आज आप क्या योगदान देना चाहते हैं?',
      'create_sub': 'सकारात्मक बदलाव लाने का तरीका चुनें:',
      'create_do_action': 'कार्य करें',
      'create_do_action_sub': 'सूची से कार्य चुनें, पहले/बाद की तस्वीर लें और कर्म कमाएं।',
      'create_report_prob': 'समस्या दर्ज करें',
      'create_report_prob_sub': 'जीपीएस के साथ किसी समस्या (कचरा, गड्ढा, टूटी पाइप) की तस्वीर लें।',
      'create_make_wish': 'इच्छा बनाएं',
      'create_make_wish_sub': 'शिक्षा, चिकित्सा या आवश्यक जरूरतों के लिए समुदाय से मदद मांगें।',
      'create_propose': 'नया कार्य प्रस्तावित करें',
      'create_propose_sub': 'वैश्विक कर्म सूची में नया कार्य जोड़ने का प्रस्ताव दें।',
      'create_suggest': 'सुझाव दें',
      'create_suggest_sub': 'विचार साझा करके या बग की रिपोर्ट करके कर्म ग्रिड को बेहतर बनाएं।',
      'create_badge_action': '+20 से +100 कर्म कमाएं',
      'create_badge_report': '+20 कर्म व +10 विश्वास कमाएं',
      'create_badge_wish': 'समुदाय समर्थित',
      'create_badge_propose': 'गवर्नेंस सहमति',
      'create_badge_suggest': 'ऐप सुधार',
      'disc_tab_actions': '🌱 कार्य',
      'disc_tab_problems': '🚨 समस्याएं',
      'disc_tab_challenges': '🏆 चुनौतियां',
      'disc_tab_orgs': '🤝 संगठन',
      'disc_tab_missions': '🇮🇳 मिशन व एआई',
      'disc_search_hint': 'कार्य, समस्याएं या संस्थाएं खोजें...',
      'disc_do_this': 'यह करें',
      'disc_fix_earn': 'सुधारें व कमाएं',
      'disc_join': 'जुड़ें',
      'disc_no_problems': 'आपके क्षेत्र में कोई अनसुलझी समस्या नहीं है!',
      'disc_report_issue': 'नई समस्या दर्ज करें',
      'chal_plastic_title': 'वैश्विक प्लास्टिक सफाई अभियान 🌍',
      'chal_plastic_desc': '5 प्लास्टिक वस्तुएं एकत्र करें व फोटो लें। आज 1.5x गुणक!',
      'chal_tree_title': 'दिल्ली वृक्ष पोषण अभियान 🌳',
      'chal_tree_desc': 'अपने आस-पास के 3 नए पौधों को पानी दें।',
      'chal_animal_title': 'बेसहारा पशु शीतकालीन सहायता 🐾',
      'chal_animal_desc': 'आस-पास के बेसहारा जानवरों के लिए साफ पानी और रहने की जगह बनाएं।',
      'org_green_earth': 'ग्रीन अर्थ फाउंडेशन 🌍',
      'org_green_earth_cat': 'पर्यावरण एवं वानिकी',
      'org_apex': 'एपेक्स अकादमी 🏫',
      'org_apex_cat': 'नागरिक शिक्षा एवं युवा',
      'org_mcd': 'दिल्ली नगर निगम 🏛️',
      'org_mcd_cat': 'नागरिक स्वच्छता एवं बुनियादी ढांचा',
      'org_verified_ngo': '🛡️ सत्यापित एनजीओ • 98% विश्वास',
      'org_verified_school': '🛡️ सत्यापित स्कूल • 95% विश्वास',
      'org_verified_muni': '🛡️ सत्यापित प्राधिकरण • 92% विश्वास',
      'mission_india30_title': 'इंडिया 30 मिशन हब',
      'mission_india30_sub': 'स्वच्छ जल, कचरा निस्तारण और शिक्षा के राष्ट्रीय लक्ष्य',
      'mission_flywheel_title': 'पारिस्थितिकी तंत्र फ्लाईव्हील एवं एआई कोर',
      'mission_flywheel_sub': 'यूट्यूब कहानियां, कर्म ग्राफ और सामूहिक बुद्धिमत्ता',
      'wishes_title': '🌟 इच्छा पूर्ति केंद्र',
      'wishes_waiting': 'इच्छाएं मददगारों की प्रतीक्षा में हैं',
      'wishes_make_btn': 'इच्छा बनाएं 💫',
      'wishes_tab_my': '✨ मेरी इच्छाएं',
      'wishes_tab_help': '🌟 मैं मदद कर सकता हूँ',
      'wishes_tab_fulfilling': '❤️ पूरी हो रही हैं',
      'wishes_tab_made_possible': '✅ पूरी हो चुकी हैं',
      'wishes_empty_my': 'आपने अभी तक कोई इच्छा नहीं जोड़ी है।',
      'wishes_empty_help': 'इस श्रेणी में अभी किसी इच्छा को मदद की आवश्यकता नहीं है।',
      'wishes_empty_fulfilling': 'वर्तमान में कोई इच्छा सक्रिय रूप से प्रायोजित नहीं हो रही है।',
      'wishes_empty_completed': 'इस श्रेणी में अभी तक कोई इच्छा पूरी नहीं हुई है।',
      'wish_cat_all': 'सभी',
      'wish_sponsor_btn': 'इच्छा प्रायोजित करें',
      'settings_title': 'सेटिंग्स',
      'settings_acc_voice': 'सुलभता एवं आवाज़',
      'settings_app_mode': 'ऐप इंटरफ़ेस मोड',
      'settings_voice_lang': 'आवाज़ की भाषा',
      'settings_voice_guidance': 'आवाज़ मार्गदर्शन',
      'settings_voice_guidance_sub': 'बटन छूने पर विवरण सुनें',
      'settings_general': 'सामान्य सेटिंग्स',
      'settings_theme': 'थीम चयन',
      'settings_biometric': 'बायोमेट्रिक सुरक्षा',
      'settings_push_notif': 'पुश सूचनाएं',
      'settings_admin': 'व्यवस्थापक केंद्र',
      'settings_admin_sub': 'सत्यापन कतार एवं ऑडिट लॉग',
      'settings_support': 'सहायता एवं नियम',
      'settings_report_abuse': 'दुरुपयोग की रिपोर्ट करें',
      'settings_help_faq': 'सहायता केंद्र',
      'settings_about': 'कर्म ग्रिड के बारे में',
      'settings_logout': 'पासपोर्ट लॉग आउट',
      'eco_hub_title': 'एकीकृत फ्लाईव्हील हब',
      'eco_loop_badge': '4-चरणीय कार्य चक्र',
      'eco_loop_sub': 'प्रत्येक वास्तविक सुधार इस 4-चरणीय जीवन चक्र का पालन करता है:',
      'proof_upload_title': 'प्रमाण अपलोड केंद्र',
      'proof_select_files': 'सत्यापन फाइलें चुनें',
      'proof_desc': 'फोटो, वीडियो या ऑडियो संलग्न करें। एआई मेटाडेटा और जीपीएस से विश्वास स्कोर की गणना करेगा।',
      'proof_photo_btn': 'फोटो प्रमाण अपलोड करें (JPEG/PNG)',
      'proof_video_btn': 'वीडियो प्रमाण अपलोड करें (MP4)',
      'proof_audio_btn': 'ऑडियो गवाही अपलोड करें (WAV)',
      'proof_confirm_btn': 'पुष्टि करें और वापस जाएं',
      'talk_where_can_do': '🌱 मैं कहाँ अच्छा काम कर सकता हूँ?',
      'talk_report_garbage': '🔎 कचरा / समस्या की रिपोर्ट करें',
      'talk_how_wish': '✨ इच्छा कैसे बनाएं?',
      'talk_my_karma': '📊 मेरा कर्म स्कोर क्या है?',
    },
    'bn': {
      'app_title': 'কর্ম গ্রিড',
      'app_tagline': 'ভাল কাজের প্রমাণ',
      'nav_home': 'হোম',
      'nav_discover': 'আবিষ্কার করুন',
      'nav_create': 'তৈরি করুন',
      'nav_wishes': 'ইচ্ছা',
      'nav_me': 'প্রোফাইল',
      'dash_karma': 'কর্ম',
      'dash_impact': 'প্রভাব',
      'dash_trust': 'বিশ্বাস স্কোর',
      'dash_action_do': 'ভালো কাজ করুন',
      'dash_action_report': 'রিপোর্ট করুন',
      'dash_action_wish': 'ইচ্ছা প্রকাশ করুন',
      'dash_action_help_wish': 'ইচ্ছায় সাহায্য করুন',
      'login_title': 'আপনার কর্ম পাসপোর্ট অ্যাক্সেস করুন',
      'login_btn': 'লগ ইন করুন',
      'login_btn_create': 'অ্যাকাউন্ট তৈরি করুন',
      'unit_credits': 'ক্রেডিট',
      'unit_verified': 'যাচাইকৃত',
      'unit_rating': 'রেটিং',
    },
    'ta': {
      'app_title': 'கர்மா கிரிட்',
      'app_tagline': 'நன்மைக்கான சான்று',
      'nav_home': 'முகப்பு',
      'nav_discover': 'கண்டறியவும்',
      'nav_create': 'உருவாக்கு',
      'nav_wishes': 'விருப்பங்கள்',
      'nav_me': 'சுயவிவரம்',
      'dash_karma': 'கர்மா',
      'dash_impact': 'தாக்கம்',
      'dash_trust': 'நம்பிக்கை மதிப்பெண்',
      'dash_action_do': 'நல்லது செய்யுங்கள்',
      'dash_action_report': 'புகாரளிக்கவும்',
      'dash_action_wish': 'விருப்பம் கோருங்கள்',
      'dash_action_help_wish': 'விருப்பத்திற்கு உதவுங்கள்',
      'login_title': 'உங்கள் கர்மா கடவுச்சீட்டை அணுகவும்',
      'login_btn': 'உள்நுழைக',
      'login_btn_create': 'கணக்கை உருவாக்கவும்',
      'unit_credits': 'மதிப்பெண்கள்',
      'unit_verified': 'சரிபார்க்கப்பட்டது',
      'unit_rating': 'மதிப்பீடு',
    },
    'te': {
      'app_title': 'కర్మ గ్రిడ్',
      'app_tagline': 'మంచి పనికి రుజువు',
      'nav_home': 'హోమ్',
      'nav_discover': 'కనుగొనండి',
      'nav_create': 'సృష్టించండి',
      'nav_wishes': 'కోరికలు',
      'nav_me': 'ప్రొఫైల్',
      'dash_karma': 'కర్మ',
      'dash_impact': 'ప్రభావం',
      'dash_trust': 'విశ్వసనీయత స్కోర్',
      'dash_action_do': 'మంచి చేయండి',
      'dash_action_report': 'సమస్యను నివేదించండి',
      'dash_action_wish': 'కోరికను కోరండి',
      'dash_action_help_wish': 'కోరికకు సహాయం చేయండి',
      'login_title': 'మీ కర్మ పాస్‌పోర్ట్‌ను తెరవండి',
      'login_btn': 'లాగిన్ చేయండి',
      'login_btn_create': 'ఖాతాను సృష్టించండి',
      'unit_credits': 'క్రెడిట్లు',
      'unit_verified': 'ధృవీకరించబడింది',
      'unit_rating': 'రేటింగ్',
    },
    'mr': {
      'app_title': 'कर्म ग्रिड',
      'app_tagline': 'चांगुलपणाचा पुरावा',
      'nav_home': 'मुख्यपृष्ठ',
      'nav_discover': 'शोधा',
      'nav_create': 'तयार करा',
      'nav_wishes': 'इच्छा',
      'nav_me': 'माझे प्रोफाइल',
      'dash_karma': 'कर्म',
      'dash_impact': 'प्रभाव',
      'dash_trust': 'विश्वास स्कोअर',
      'dash_action_do': 'चांगले काम करा',
      'dash_action_report': 'तक्रार नोंदवा',
      'dash_action_wish': 'इच्छा मागा',
      'dash_action_help_wish': 'इच्छेला मदत करा',
      'login_title': 'आपला कर्म पासपोर्ट उघडा',
      'login_btn': 'लॉग इन करा',
      'login_btn_create': 'खाते तयार करा',
      'unit_credits': 'क्रेडिट्स',
      'unit_verified': 'प्रमाणित',
      'unit_rating': 'रेटिंग',
    },
    'ur': {
      'app_title': 'کرما گرڈ',
      'app_tagline': 'نیکی کا ثبوت',
      'nav_home': 'ہوم',
      'nav_discover': 'دریافت کریں',
      'nav_create': 'تخلیق کریں',
      'nav_wishes': 'خواہشات',
      'nav_me': 'پروفائل',
      'dash_karma': 'کرما',
      'dash_impact': 'اثر',
      'dash_trust': 'اعتماد کا اسکور',
      'dash_action_do': 'نیکی کریں',
      'dash_action_report': 'مسئلہ درج کریں',
      'dash_action_wish': 'خواہش کا اظہار کریں',
      'dash_action_help_wish': 'خواہش پوری کرنے میں مدد کریں',
      'login_title': 'اپنے کرما پاسپورٹ تک رسائی حاصل کریں',
      'login_btn': 'لاگ ان کریں',
      'login_btn_create': 'اکاؤنٹ بنائیں',
      'unit_credits': 'کریڈٹس',
      'unit_verified': 'تصدیق شدہ',
      'unit_rating': 'درجہ بندی',
    },
    'he': {
      'app_title': 'קארמה גריד',
      'app_tagline': 'הוכחה למעשים טובים',
      'nav_home': 'בית',
      'nav_discover': 'גלה',
      'nav_create': 'צור',
      'nav_wishes': 'משאלות',
      'nav_me': 'פרופיל',
      'dash_karma': 'קארמה',
      'dash_impact': 'השפעה',
      'dash_trust': 'ציון אמון',
      'dash_action_do': 'עשה טוב',
      'dash_action_report': 'דווח על בעיה',
      'dash_action_wish': 'בקש משאלה',
      'dash_action_help_wish': 'עזור למשאלה',
      'login_title': 'גש לדרכון הקארמה שלך',
      'login_btn': 'התחבר',
      'login_btn_create': 'צור חשבון',
      'unit_credits': 'קרדיטים',
      'unit_verified': 'מאומת',
      'unit_rating': 'דירוג',
    },
    'ar': {
      'app_title': 'كارما جريد',
      'app_tagline': 'إثبات الخير والعمل الصالح',
      'nav_home': 'الرئيسية',
      'nav_discover': 'استكشف',
      'nav_create': 'إنشاء',
      'nav_wishes': 'الأمنيات',
      'nav_me': 'الملف الشخصي',
      'dash_karma': 'كارما',
      'dash_impact': 'الأثر',
      'dash_trust': 'درجة الثقة',
      'dash_action_do': 'افعل الخير',
      'dash_action_report': 'أبلغ عن مشكلة',
      'dash_action_wish': 'اطلب أمنية',
      'dash_action_help_wish': 'ساعد في أمنية',
      'login_title': 'الوصول إلى جواز سفر كارما',
      'login_btn': 'تسجيل الدخول',
      'login_btn_create': 'إنشاء حساب',
      'unit_credits': 'نقاط',
      'unit_verified': 'موثق',
      'unit_rating': 'التقييم',
    },
  };

  // DICTIONARY 2: Universal Phrase & Term Dictionary (Maps direct English text to target language)
  static const Map<String, Map<String, String>> _phraseDictionary = {
    'hi': {
      // General Words & UI
      'Home': 'होम',
      'Discover': 'खोजें',
      'Create': 'बनाएं',
      'Wishes': 'इच्छाएं',
      'Me': 'प्रोफ़ाइल',
      'Passport': 'पासपोर्ट',
      'Karma': 'कर्म',
      'Impact': 'प्रभाव',
      'Trust Score': 'विश्वास स्कोर',
      'Karma Passport': 'कर्म पासपोर्ट',
      'Karma Credits': 'कर्म क्रेडिट्स',
      'Credits': 'क्रेडिट्स',
      'Verified': 'सत्यापित',
      'Rating': 'रेटिंग',
      'Effort': 'प्रयास',
      'Reward': 'पुरस्कार',
      'Volunteers': 'स्वयंसेवक',
      'Deeds': 'कार्य',
      'Settings': 'सेटिंग्स',
      'Logout': 'लॉग आउट',
      'Login': 'लॉग इन',
      'Create Account': 'खाता बनाएं',
      'Full Name': 'पूरा नाम',
      'Password': 'पासवर्ड',
      'Email or Phone': 'ईमेल या फ़ोन',
      'Confirm & Return': 'पुष्टि करें और वापस जाएं',
      'Submit': 'जमा करें',
      'Cancel': 'रद्द करें',
      'Close': 'बंद करें',
      'Save': 'सहेजें',
      'Back': 'पीछे',
      'Next': 'आगे',
      'Join': 'जुड़ें',
      'Do This': 'यह करें',
      'Fix & Earn': 'सुधारें व कमाएं',
      'Make a Wish 💫': 'इच्छा बनाएं 💫',
      'Make a Wish': 'इच्छा बनाएं',
      'Help a Wish': 'इच्छा में मदद करें',
      'Report a Problem': 'समस्या दर्ज करें',
      'Do an Action': 'कार्य करें',
      'Add an Action Proposal': 'नया कार्य प्रस्तावित करें',
      'Suggest an Improvement': 'सुझाव दें',
      'All': 'सभी',
      'Easy': 'सरल',
      'Medium': 'मध्यम',
      'High': 'कठिन',
      'Critical': 'अति महत्वपूर्ण',
      'Okay': 'ठीक',
      'Difficult': 'कठिन',
      'Low': 'कम',

      // Categories
      'ENVIRONMENT': 'पर्यावरण',
      'ANIMAL_WELFARE': 'पशु कल्याण',
      'EDUCATION': 'शिक्षा',
      'HEALTHCARE': 'स्वास्थ्य सेवा',
      'HEALTH': 'स्वास्थ्य',
      'COMMUNITY': 'समुदाय',
      'COMMUNITY_SERVICE': 'सामुदायिक सेवा',
      'CIVIC_INFRASTRUCTURE': 'नागरिक अवसंरचना',
      'DISASTER_RELIEF': 'आपदा राहत',
      'ELDERLY_SUPPORT': 'वृद्ध सहायता',
      'CLEAN_ENERGY': 'स्वच्छ ऊर्जा',
      'WATER_CONSERVATION': 'जल संरक्षण',
      'FOOD_SECURITY': 'खाद्य सुरक्षा',
      'DIGITAL_LITERACY': 'डिजिटल साक्षरता',
      'Environment': 'पर्यावरण',
      'Animal Welfare': 'पशु कल्याण',
      'Education': 'शिक्षा',
      'Healthcare': 'स्वास्थ्य सेवा',
      'Health': 'स्वास्थ्य',
      'Community': 'समुदाय',
      'Community Service': 'सामुदायिक सेवा',
      'Civic Infrastructure': 'नागरिक अवसंरचना',
      'Water Conservation': 'जल संरक्षण',
      'Digital Literacy': 'डिजिटल साक्षरता',
      'environment': 'पर्यावरण',
      'animalWelfare': 'पशु कल्याण',
      'education': 'शिक्षा',
      'healthcare': 'स्वास्थ्य सेवा',
      'communityService': 'सामुदायिक सेवा',
      'civicInfrastructure': 'नागरिक अवसंरचना',
      'waterConservation': 'जल संरक्षण',
      'digitalLiteracy': 'डिजिटल साक्षरता',

      // Statuses
      'PENDING': 'लंबित',
      'VERIFIED': 'सत्यापित',
      'REJECTED': 'अस्वीकृत',
      'ACTIVE': 'सक्रिय',
      'FULFILLED': 'पूर्ण',
      'RESOLVED & VERIFIED': 'समाधान एवं सत्यापित',
      'ADOPTED BY SHELTER': 'आश्रय स्थल द्वारा अपनाया गया',

      // Missions & India 30
      'India 30 Mission Hub 🇮🇳': 'इंडिया 30 मिशन हब 🇮🇳',
      'India 30 Mission Hub': 'इंडिया 30 मिशन हब',
      'INDIA 30 NATIONAL OBJECTIVES': 'इंडिया 30 राष्ट्रीय उद्देश्य',
      'National Progress Metrics (Live)': 'राष्ट्रीय प्रगति मेट्रिक्स (लाइव)',
      'Human Capital & Education': 'मानव पूंजी एवं शिक्षा',
      'Environmental Security': 'पर्यावरण सुरक्षा',
      'Civic Infrastructure & Health': 'नागरिक अवसंरचना एवं स्वास्थ्य',
      '30 foundational priority actions selected specifically to improve human capital, environmental security, and civic infrastructure in India. Earn Karma Multipliers for community-wide reach.': 'भारत में मानव पूंजी, पर्यावरण सुरक्षा और नागरिक अवसंरचना में सुधार के लिए चुने गए 30 प्राथमिकता वाले कार्य। समुदाय-व्यापी पहुंच के लिए कर्म गुणक अर्जित करें।',
      'Ecosystem Flywheel & AI Core': 'पारिस्थितिकी तंत्र फ्लाईव्हील एवं एआई कोर',
      'YouTube Stories, Karma Graph, and Collective Intelligence Query Engine': 'यूट्यूब कहानियां, कर्म ग्राफ और सामूहिक बुद्धिमत्ता खोज इंजन',

      // Common Deed titles
      "Save a person's life during an emergency.": "आपातकाल के दौरान किसी व्यक्ति की जान बचाएं।",
      "Donate a kidney or other eligible organ to save another person's life.": "किसी अन्य व्यक्ति का जीवन बचाने के लिए अंग दान करें।",
      "Become a registered organ donor.": "पंजीकृत अंग दाता बनें।",
      "Donate blood when medically eligible.": "रक्तदान करें।",
      "Plant a native tree sapling and commit to nurturing it.": "एक देशी पेड़ का पौधा लगाएं और उसकी देखभाल करें।",
      "Plant a native tree sapling.": "एक देशी पेड़ का पौधा लगाएं।",
      "Segregate wet and dry household waste for a month.": "एक महीने तक गीला और सूखा कचरा अलग-अलग करें।",
      "Clean up a public park or street litter.": "सार्वजनिक पार्क या सड़क से कचरा साफ करें।",
      "Feed stray animals with safe food and water.": "बेसहारा पशुओं को सुरक्षित भोजन और पानी दें।",
      "Teach a child or student mentorship session.": "किसी बच्चे या छात्र को पढ़ाएं।",
      "Donate books to a public library or school.": "पुस्तकालय या स्कूल को पुस्तकें दान करें।",
      "Plastic Recovery & Segregation": "प्लास्टिक कचरा निष्कासन व पृथक्करण",
      "Neighborhood Composting Drive": "सामुदायिक खाद अभियान",
      "Delhi Tree Nurture Drive 🌳": "दिल्ली वृक्ष पोषण अभियान 🌳",
      "Global Plastic Recovery Drive 🌍": "वैश्विक प्लास्टिक सफाई अभियान 🌍",
      "Stray Animal Winter Aid 🐾": "बेसहारा पशु शीतकालीन सहायता 🐾",
      "Garbage dump near school gate": "स्कूल गेट के पास कचरे का ढेर",
      "Injured street puppy in Sector 4": "सेक्टर 4 में घायल गली का पिल्ला",
      "Broken water pipe flooding market road": "बाजार की सड़क पर टूटी पानी की पाइप",

      // Wishes
      "Need 10 Braille Books for Visually Impaired Kids": "दृष्टिबाधित बच्चों के लिए 10 ब्रेल पुस्तकें",
      "Solar Lantern for Tribal School Evening Classes": "आदिवासी स्कूल की शाम की कक्षाओं के लिए सोलर लालटेन",
      "Prosthetic Foot for Rural Farmer": "ग्रामीण किसान के लिए कृत्रिम पैर",
      "Wheelchair for Community Center Ramp Access": "सामुदायिक केंद्र के लिए व्हीलचेयर",
      "Science Lab Equipment for Rural High School": "ग्रामीण हाई स्कूल के लिए विज्ञान प्रयोगशाला उपकरण",
      "Medical Oxygen Concentrator for Village Clinic": "ग्राम क्लिनिक के लिए मेडिकल ऑक्सीजन कंसंट्रेटर",
      "You haven't submitted any wishes yet.": "आपने अभी तक कोई इच्छा नहीं जोड़ी है।",
      "No wishes matching this category need help right now.": "इस श्रेणी में अभी किसी इच्छा को मदद की आवश्यकता नहीं है।",
      "No wishes are currently receiving active sponsorship.": "वर्तमान में कोई इच्छा प्रायोजित नहीं हो रही है।",
      "No wishes have been fully completed in this category yet.": "इस श्रेणी में अभी तक कोई इच्छा पूरी नहीं हुई है।",

      // Organizations
      "Green Earth Foundation 🌍": "ग्रीन अर्थ फाउंडेशन 🌍",
      "Apex Academy 🏫": "एपेक्स अकादमी 🏫",
      "Municipal Corporation Delhi 🏛️": "दिल्ली नगर निगम 🏛️",
      "Environment & Forestry": "पर्यावरण एवं वानिकी",
      "Civic Education & Youth": "नागरिक शिक्षा एवं युवा",
      "Civic Sanitation & Infrastructure": "नागरिक स्वच्छता एवं बुनियादी ढांचा",
      "🛡️ Verified NGO • 98% Trust": "🛡️ सत्यापित एनजीओ • 98% विश्वास",
      "🛡️ Verified School • 95% Trust": "🛡️ सत्यापित स्कूल • 95% विश्वास",
      "🛡️ Verified Authority • 92% Trust": "🛡️ सत्यापित प्राधिकरण • 92% विश्वास",

      // Feedbacks
      "Give Feedback 💡": "प्रतिक्रिया दें 💡",
      "Community Ideas 👥": "सामुदायिक विचार 👥",
      "Was this step easy?": "क्या यह चरण आसान था?",
      "Tell us what happened or what could be better...": "बताएं कि क्या हुआ या क्या बेहतर हो सकता है...",

      // Deed Submission & Verification Screen
      'Curated Positive Actions (366 Presets)': 'क्यूरेटेड सकारात्मक कार्य (366 प्रीसेट)',
      'Search leap-year master list...': 'लीप-वर्ष मास्टर सूची खोजें...',
      'e.g., cpr, recycle, mentor, feed...': 'उदा. प्राथमिक चिकित्सा, रीसायकल, पढ़ाना, भोजन...',
      'Can\'t find your deed? Propose a new Action to the registry': 'अपना कार्य नहीं मिला? रजिस्ट्री में एक नया कार्य प्रस्तावित करें',
      'Taxonomy Match: Tier': 'वर्गीकरण मिलान: टियर',
      'Base Impact:': 'मूल प्रभाव:',
      'Base Impact': 'मूल प्रभाव',
      'Effort Level:': 'प्रयास स्तर:',
      'Frequency Limit:': 'आवृत्ति सीमा:',
      'Required Verification:': 'आवश्यक सत्यापन:',
      'Warning: This action requires GPS location and photo proof for verification.': 'चेतावनी: इस कार्य के सत्यापन के लिए जीपीएस स्थान और फोटो प्रमाण आवश्यक है।',
      'Verification Level Ladder': 'सत्यापन स्तर सीढ़ी',
      '🟢 Self': '🟢 स्वयं',
      '🔵 Evidence': '🔵 प्रमाण',
      '🟣 Community': '🟣 समुदाय',
      '🟠 Org': '🟠 संस्था',
      '🔴 Independent': '🔴 स्वतंत्र',
      'Self-verification for tiny actions': 'छोटे कार्यों के लिए स्व-सत्यापन',
      'Photos, location and timestamps': 'फोटो, स्थान और समय-मुहर',
      'Peer validator consensus': 'सहकर्मी सत्यापनकर्ता सहमति',
      'Official NGO/institution signature': 'आधिकारिक एनजीओ/संस्था हस्ताक्षर',
      'Independent third-party audits': 'स्वतंत्र तृतीय-पक्ष ऑडिट',
      'Activity Title': 'कार्य का शीर्षक',
      'e.g., Planted saplings, Fed animals...': 'उदा. पौधे लगाए, जानवरों को खाना खिलाया...',
      'Enter a title': 'कृपया एक शीर्षक दर्ज करें',
      'Describe your contribution': 'अपने योगदान का विवरण दें',
      'What did you do? Who did it benefit? Include any key context.': 'आपने क्या किया? इससे किसे लाभ हुआ? मुख्य संदर्भ शामिल करें।',
      'Please provide a detailed description (min 10 characters)': 'कृपया विस्तृत विवरण प्रदान करें (कम से कम 10 अक्षर)',
      'Scale of Action (People/Units helped)': 'कार्य का पैमाना (मदद किए गए व्यक्ति/इकाइयां)',
      'e.g. 1 (individual), 20 (group), 1000 (scaled course/tool)': 'उदा. 1 (व्यक्तिगत), 20 (समूह), 1000 (उपकरण/पाठ्यक्रम)',
      'Enter the scale of action': 'कार्य का पैमाना दर्ज करें',
      'Enter a valid positive number': 'एक मान्य धनात्मक संख्या दर्ज करें',
      'Duration Type': 'अवधि प्रकार',
      '⚡ Quick (1-15m)': '⚡ त्वरित (1-15 मिनट)',
      '🌱 Deep (hours/days)': '🌱 गहरा (घंटे/दिन)',
      '🚀 Impact (project)': '🚀 प्रभाव (प्रोजेक्ट)',
      'Impact Scope': 'प्रभाव का दायरा',
      'Individual': 'व्यक्तिगत',
      'Team': 'टीम',
      'City': 'शहर',
      'Global': 'वैश्विक',
      'Stake Proof Bond (20 Reputation)': 'प्रमाण बॉन्ड स्टेक करें (20 प्रतिष्ठा)',
      'Required for Level 4/5 actions. Bond is forfeited on fraudulent claims.': 'स्तर 4/5 कार्यों के लिए आवश्यक। झूठे दावों पर बॉन्ड जब्त हो जाएगा।',
      'Vulnerable Person Protection': 'संवेदनशील व्यक्ति सुरक्षा',
      'Protects patients/kids. Uses QR codes/receipts instead of photo proof.': 'रोगियों/बच्चों की सुरक्षा। फोटो के स्थान पर क्यूआर कोड/रसीद का उपयोग।',
      'Anonymized Witness QR Code / Receipt ID': 'गुमनाम गवाह क्यूआर कोड / रसीद आईडी',
      'e.g. Blood bank donation code, shelter registration QR': 'उदा. ब्लड बैंक दान कोड, आश्रय पंजीकरण क्यूआर',
      'Creativity Bonus (+10% credits)': 'रचनात्मकता बोनस (+10% क्रेडिट)',
      'Creative methods, art, or unique solutions applied.': 'लागू की गई रचनात्मक विधियां, कला या अनूठे समाधान।',
      'Group Participation Bonus (+15% credits)': 'समूह भागीदारी बोनस (+15% क्रेडिट)',
      'Completed with friends, family, or teams.': 'दोस्तों, परिवार या टीम के साथ पूरा किया गया।',
      'Ripple Inspiration Bonus (+20% credits)': 'रिपल प्रेरणा बोनस (+20% क्रेडिट)',
      'Directly inspired others to join or copy the activity.': 'दूसरों को इस कार्य में शामिल होने या दोहराने के लिए प्रेरित किया।',
      'Select Category': 'श्रेणी चुनें',
      'Launch guided Proof Capture Mode': 'मार्गदर्शित प्रमाण कैप्चर मोड प्रारंभ करें',
      '🔐 Secure Proof Capture Verified': '🔐 सुरक्षित प्रमाण कैप्चर सत्यापित',
      'Attach Proof of Change (Required)': 'बदलाव का प्रमाण संलग्न करें (आवश्यक)',
      'No Proof of Change, No Impact Credit: You must attach both BEFORE and AFTER evidence to verify your impact.': 'बदलाव का कोई प्रमाण नहीं, कोई प्रभाव क्रेडिट नहीं: प्रभाव सत्यापित करने के लिए पहले और बाद दोनों के प्रमाण संलग्न करना अनिवार्य है।',
      'BEFORE Attached': 'पहले का प्रमाण संलग्न',
      'Attach BEFORE': 'पहले की तस्वीर',
      'AFTER Attached': 'बाद का प्रमाण संलग्न',
      'Attach AFTER': 'बाद की तस्वीर',
      'Fetching...': 'प्राप्त कर रहे हैं...',
      'GPS Verified': 'जीपीएस सत्यापित',
      'Fetch Location': 'स्थान प्राप्त करें',
      'Evidence Type Guidelines for': 'प्रमाण प्रकार दिशानिर्देश',
      'BEFORE Check-in / Initial Assessment': 'पहले: चेक-इन / प्रारंभिक मूल्यांकन',
      'BEFORE Initial Assessment / Syllabus': 'पहले: प्रारंभिक मूल्यांकन / पाठ्यक्रम',
      'BEFORE Condition Photo': 'पहले: स्थिति की तस्वीर',
      'BEFORE Starting Condition Proof': 'पहले: प्रारंभिक स्थिति का प्रमाण',
      'AFTER Donation Receipt': 'बाद में: दान रसीद',
      'AFTER Final Assessment / Outcome': 'बाद में: अंतिम परिणाम / मूल्यांकन',
      'AFTER Resulting State Photo': 'बाद में: परिणामी स्थिति की तस्वीर',
      'AFTER Resulting Change Proof': 'बाद में: परिणामी बदलाव का प्रमाण',
      'Open advanced Proof Upload Hub (MP4 / WAV)': 'उन्नत प्रमाण अपलोड हब खोलें (MP4 / WAV)',
      'Community Witness Email (Optional)': 'सामुदायिक गवाह ईमेल (वैकल्पिक)',
      'e.g., recipient, observer, or NGO head': 'उदा. प्राप्तकर्ता, पर्यवेक्षक, या एनजीओ प्रमुख',
      'Projected Proof Strength': 'अनुमानित प्रमाण शक्ति',
      'Confidence': 'विश्वास',
      'Excellent proof! Validators will process this submission immediately.': 'उत्कृष्ट प्रमाण! सत्यापनकर्ता इस कार्य को तुरंत सत्यापित करेंगे।',
      'Good proof. Highly eligible for verification and standard rewards.': 'अच्छा प्रमाण। सत्यापन और मानक पुरस्कारों के लिए पात्र।',
      'Weak proof. Submissions with low proof require extra manual validators.': 'कमजोर प्रमाण। कम प्रमाण वाले कार्यों के लिए अतिरिक्त सत्यापन की आवश्यकता होती है।',
      'Scale Multiplier:': 'पैमाना गुणक:',
      'Direct:': 'प्रत्यक्ष:',
      'Ripple Factor:': 'रिपल प्रभाव:',
      'Ripple:': 'रिपल:',
      'Projected Total Payout': 'अनुमानित कुल भुगतान',
      'Track AI verification steps': 'एआई सत्यापन चरण ट्रैक करें',
      'Submit to Ledger Queue': 'लेजर कतार में जमा करें',
    },
  };

  /// Main translation function that resolves keys, phrases, categories, and dynamic terms
  static String translate(String keyOrText, {String lang = 'en', String defaultValue = ''}) {
    final cleanLang = _normalizeLangCode(lang);
    
    // 1. Direct Key Match
    if (_localizedValues.containsKey(cleanLang) && _localizedValues[cleanLang]!.containsKey(keyOrText)) {
      return _localizedValues[cleanLang]![keyOrText]!;
    }

    // 2. Direct Phrase Match
    if (_phraseDictionary.containsKey(cleanLang) && _phraseDictionary[cleanLang]!.containsKey(keyOrText)) {
      return _phraseDictionary[cleanLang]![keyOrText]!;
    }

    final trimmed = keyOrText.trim();
    if (_phraseDictionary.containsKey(cleanLang) && _phraseDictionary[cleanLang]!.containsKey(trimmed)) {
      return _phraseDictionary[cleanLang]![trimmed]!;
    }

    // 3. Dynamic Term Substitution for Compound Phrases in Hindi
    if (cleanLang == 'hi') {
      String translated = keyOrText;
      bool matched = false;

      if (translated.contains('Karma Credits')) {
        translated = translated.replaceAll('Karma Credits', 'कर्म क्रेडिट्स');
        matched = true;
      }
      if (translated.contains('Karma')) {
        translated = translated.replaceAll('Karma', 'कर्म');
        matched = true;
      }
      if (translated.contains('Credits')) {
        translated = translated.replaceAll('Credits', 'क्रेडिट्स');
        matched = true;
      }
      if (translated.contains('Verified')) {
        translated = translated.replaceAll('Verified', 'सत्यापित');
        matched = true;
      }
      if (translated.contains('Rating')) {
        translated = translated.replaceAll('Rating', 'रेटिंग');
        matched = true;
      }
      if (translated.contains('Trust')) {
        translated = translated.replaceAll('Trust', 'विश्वास');
        matched = true;
      }
      if (translated.contains('Deeds')) {
        translated = translated.replaceAll('Deeds', 'कार्य');
        matched = true;
      }
      if (translated.contains('volunteers')) {
        translated = translated.replaceAll('volunteers', 'स्वयंसेवक');
        matched = true;
      }
      if (translated.contains('Effort')) {
        translated = translated.replaceAll('Effort', 'प्रयास');
        matched = true;
      }
      if (translated.contains('Medium')) {
        translated = translated.replaceAll('Medium', 'मध्यम');
        matched = true;
      }
      if (translated.contains('Low')) {
        translated = translated.replaceAll('Low', 'सरल');
        matched = true;
      }
      if (translated.contains('High')) {
        translated = translated.replaceAll('High', 'कठिन');
        matched = true;
      }
      if (translated.contains('Critical')) {
        translated = translated.replaceAll('Critical', 'अति महत्वपूर्ण');
        matched = true;
      }
      if (translated.contains('Status: RESOLVED & VERIFIED')) {
        translated = translated.replaceAll('Status: RESOLVED & VERIFIED', 'स्थिति: समाधान एवं सत्यापित');
        matched = true;
      }
      if (translated.contains('Status: ADOPTED BY SHELTER')) {
        translated = translated.replaceAll('Status: ADOPTED BY SHELTER', 'स्थिति: आश्रय स्थल द्वारा अपनाया गया');
        matched = true;
      }
      if (translated.contains('Status: PENDING')) {
        translated = translated.replaceAll('Status: PENDING', 'स्थिति: लंबित');
        matched = true;
      }
      if (translated.contains('Status: VERIFIED')) {
        translated = translated.replaceAll('Status: VERIFIED', 'स्थिति: सत्यापित');
        matched = true;
      }
      if (translated.startsWith('By ')) {
        translated = translated.replaceFirst('By ', 'द्वारा ');
        matched = true;
      }
      if (translated.contains('wishes waiting for sponsors')) {
        translated = translated.replaceAll('wishes waiting for sponsors', 'इच्छाएं मददगारों की प्रतीक्षा में हैं');
        matched = true;
      }

      if (matched) {
        return translated;
      }
    }

    // 4. Fallback to English Key Dictionary
    if (_localizedValues['en']!.containsKey(keyOrText)) {
      return _localizedValues['en']![keyOrText]!;
    }

    // 5. Return provided default or original string
    return defaultValue.isNotEmpty ? defaultValue : keyOrText;
  }

  static String translateWithContext(BuildContext context, String keyOrText, {String defaultValue = ''}) {
    try {
      final auth = Provider.of<AuthProvider>(context, listen: false);
      return translate(keyOrText, lang: auth.currentLanguage, defaultValue: defaultValue);
    } catch (_) {
      return translate(keyOrText, lang: 'en', defaultValue: defaultValue);
    }
  }

  static String _normalizeLangCode(String lang) {
    final lower = lang.toLowerCase().trim();
    for (final l in supportedLanguages) {
      if (l['code'] == lower || l['name']!.toLowerCase() == lower || l['native']!.toLowerCase() == lower) {
        return l['code']!;
      }
    }
    return 'en';
  }
}

extension LocalizedStringExtension on String {
  String tr(BuildContext context, {String defaultValue = ''}) {
    return AppLocalizations.translateWithContext(context, this, defaultValue: defaultValue);
  }
}
