import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/auth_provider.dart';

class AppLocalizations {
  static const List<Map<String, String>> supportedLanguages = [
    {'code': 'en', 'name': 'English', 'native': 'English', 'script': 'Latin'},
    {'code': 'hi', 'name': 'Hindi', 'native': 'हिन्दी', 'script': 'Devanagari'},
    {'code': 'bn', 'name': 'Bengali', 'native': 'বাংলা', 'script': 'Bengali'},
    {'code': 'te', 'name': 'Telugu', 'native': 'తెలుగు', 'script': 'Telugu'},
    {'code': 'mr', 'name': 'Marathi', 'native': 'मराठी', 'script': 'Devanagari'},
    {'code': 'ta', 'name': 'Tamil', 'native': 'தமிழ்', 'script': 'Tamil'},
    {'code': 'ur', 'name': 'Urdu', 'native': 'اردو', 'script': 'Arabic-RTL'},
    {'code': 'gu', 'name': 'Gujarati', 'native': 'ગુજરાતી', 'script': 'Gujarati'},
    {'code': 'kn', 'name': 'Kannada', 'native': 'ಕನ್ನಡ', 'script': 'Kannada'},
    {'code': 'or', 'name': 'Odia', 'native': 'ଓଡ଼ିଆ', 'script': 'Odia'},
    {'code': 'ml', 'name': 'Malayalam', 'native': 'മലയാളം', 'script': 'Malayalam'},
    {'code': 'pa', 'name': 'Punjabi', 'native': 'ਪੰਜਾਬੀ', 'script': 'Gurmukhi'},
    {'code': 'as', 'name': 'Assamese', 'native': 'অসমীয়া', 'script': 'Bengali-Assamese'},
    {'code': 'mai', 'name': 'Maithili', 'native': 'मैथिली', 'script': 'Devanagari'},
    {'code': 'sat', 'name': 'Santali', 'native': 'ᱥᱟᱱᱛᱟᱲᱤ', 'script': 'Ol Chiki'},
    {'code': 'ks', 'name': 'Kashmiri', 'native': 'کٲشُر', 'script': 'Arabic-RTL'},
    {'code': 'ne', 'name': 'Nepali', 'native': 'नेपाली', 'script': 'Devanagari'},
    {'code': 'kok', 'name': 'Konkani', 'native': 'कोंकणी', 'script': 'Devanagari'},
    {'code': 'doi', 'name': 'Dogri', 'native': 'डोगरी', 'script': 'Devanagari'},
    {'code': 'sd', 'name': 'Sindhi', 'native': 'سنڌي', 'script': 'Arabic-RTL'},
    {'code': 'brx', 'name': 'Bodo', 'native': 'बड़ो', 'script': 'Devanagari'},
    {'code': 'sa', 'name': 'Sanskrit', 'native': 'संस्कृतम्', 'script': 'Devanagari'},
    {'code': 'mni', 'name': 'Manipuri', 'native': 'ꯃꯤꯇꯩꯂꯣꯟ', 'script': 'Meitei Mayek'},
    {'code': 'he', 'name': 'Hebrew', 'native': 'עברית', 'script': 'Hebrew-RTL'},
    {'code': 'ar', 'name': 'Arabic', 'native': 'العربية', 'script': 'Arabic-RTL'},
  ];

  static bool isRtlLanguage(String langCodeOrName) {
    final lower = langCodeOrName.toLowerCase().trim();
    return lower == 'ur' || lower == 'urdu' ||
           lower == 'he' || lower == 'hebrew' ||
           lower == 'ar' || lower == 'arabic' ||
           lower == 'ks' || lower == 'kashmiri' ||
           lower == 'sd' || lower == 'sindhi';
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'nav_home': 'Home',
      'nav_discover': 'Discover',
      'nav_create': 'Create',
      'nav_wishes': 'Wishes',
      'nav_me': 'Me',
      'app_title': 'Karma Grid',
      'app_tagline': 'Proof of Good',
      'app_hero_sub': 'Do good. Show the difference. Create verified impact.',
      'login_title': 'Access Your Karma Passport',
      'login_subtitle': 'Sign in securely with Google to record actions & earn Karma',
      'login_google_btn': 'Continue with Google / Gmail',
      'dash_welcome': 'Welcome back',
      'dash_metrics': 'Ecosystem metrics',
      'dash_karma': 'Karma',
      'dash_impact': 'Impact',
      'dash_trust': 'Trust Score',
      'dash_action_do': '🌱 DO GOOD',
      'dash_action_do_sub': 'Find a deed & prove impact',
      'dash_action_report': '🔎 REPORT',
      'dash_action_report_sub': 'Report a local problem',
      'dash_action_wish': '✨ MAKE A WISH',
      'dash_action_wish_sub': 'Ask community for help',
      'dash_action_help_wish': '🤝 HELP A WISH',
      'dash_action_help_wish_sub': 'Support someone in need',
      'dash_search_placeholder': '🔎 Search actions, problems, NGOs, schools, wishes...',
      'dash_talk_mic': '🎙️ Talk to Karma',
      'dash_talk_desc': 'Speak in your language to find actions or report problems',
      'step_before': 'BEFORE 📸',
      'step_before_desc': 'Photograph the situation now',
      'step_action': 'DO / FIX ⚡',
      'step_action_desc': 'Complete the positive action',
      'step_after': 'AFTER 📸',
      'step_after_desc': 'Photograph the change',
      'step_verified': 'VERIFIED ✓',
      'step_verified_desc': 'Multi-layer proof verification',
      'step_impact': 'IMPACT 🌍',
      'step_impact_desc': 'Measurable positive change',
      'step_karma': 'KARMA ✨',
      'step_karma_desc': 'Recognition & digital passport record',
      'fb_button': 'Feedback',
      'fb_title': 'Help Us Improve Karma Grid',
      'fb_subtitle': 'Share feedback in under 10 seconds',
      'fb_good': '👍 Good',
      'fb_difficult': '👎 Difficult',
      'fb_bug': '🐛 Problem',
      'fb_idea': '💡 Idea',
      'fb_voice_note': '🎙️ Record Voice Feedback',
      'fb_text_hint': 'Tell us what happened or what could be better...',
      'fb_submit': 'Submit Feedback (10s)',
      'fb_thank_you': 'Thank you! Your feedback helps everyone.',
      'demo_badge': 'Example / Demo Story',
      'demo_banner_title': 'How Proof of Good Works',
      'demo_banner_sub': 'Real change is proven through before-and-after evidence.',
      'safety_title': '🛡️ Trust & Safety Promise',
      'safety_desc': 'No crypto hype • No arbitrary daily caps • Real evidence verification • Direct-to-vendor wish support',
      'role_individual': 'Individual 👤',
      'role_group': 'Community Group 👥',
      'role_school': 'Institution / School 🏫',
      'role_ngo': 'NGO / Impact Org 🤝',
      'role_corporate': 'Business / Corporate 🏢',
      'role_government': 'Government / Civic 🏛️',
    },
    'hi': {
      'nav_home': 'होम',
      'nav_discover': 'खोजें',
      'nav_create': 'बनाएं',
      'nav_wishes': 'इच्छाएं',
      'nav_me': 'प्रोफ़ाइल',
      'app_title': 'कर्म ग्रिड',
      'app_tagline': 'अच्छाई का प्रमाण',
      'app_hero_sub': 'अच्छा करें। बदलाव दिखाएं। वास्तविक प्रभाव बनाएं।',
      'login_title': 'अपना कर्म पासपोर्ट एक्सेस करें',
      'login_subtitle': 'कर्म कमाने और कार्य दर्ज करने के लिए गूगल से साइन इन करें',
      'login_google_btn': 'Google / Gmail से जारी रखें',
      'dash_welcome': 'स्वागत है',
      'dash_metrics': 'पारिस्थितिकी तंत्र मेट्रिक्स',
      'dash_karma': 'कर्म',
      'dash_impact': 'प्रभाव',
      'dash_trust': 'विश्वास स्कोर',
      'dash_action_do': '🌱 अच्छा काम करें',
      'dash_action_do_sub': 'एक काम खोजें और प्रभाव साबित करें',
      'dash_action_report': '🔎 समस्या दर्ज करें',
      'dash_action_report_sub': 'स्थानीय समस्या की रिपोर्ट करें',
      'dash_action_wish': '✨ इच्छा बनाएं',
      'dash_action_wish_sub': 'समुदाय से मदद मांगें',
      'dash_action_help_wish': '🤝 इच्छा में मदद करें',
      'dash_action_help_wish_sub': 'जरूरतमंद की मदद करें',
      'dash_search_placeholder': '🔎 कार्य, समस्याएं, एनजीओ, स्कूल या इच्छाएं खोजें...',
      'dash_talk_mic': '🎙️ कर्म से बात करें',
      'dash_talk_desc': 'अपनी भाषा में बोलें और कार्य खोजें या समस्या बताएं',
      'step_before': 'पहले 📸',
      'step_before_desc': 'वर्तमान स्थिति की तस्वीर लें',
      'step_action': 'कार्य / सुधार ⚡',
      'step_action_desc': 'सकारात्मक कार्य पूरा करें',
      'step_after': 'बाद में 📸',
      'step_after_desc': 'बदलाव की तस्वीर लें',
      'step_verified': 'सत्यापित ✓',
      'step_verified_desc': 'बहुस्तरीय प्रमाण सत्यापन',
      'step_impact': 'प्रभाव 🌍',
      'step_impact_desc': 'मापने योग्य सकारात्मक बदलाव',
      'step_karma': 'कर्म ✨',
      'step_karma_desc': 'डिजिटल पासपोर्ट में मान्यता',
      'fb_button': 'प्रतिक्रिया',
      'fb_title': 'कर्म ग्रिड को बेहतर बनाएं',
      'fb_subtitle': '10 सेकंड में अपनी प्रतिक्रिया दें',
      'fb_good': '👍 अच्छा',
      'fb_difficult': '👎 कठिन',
      'fb_bug': '🐛 समस्या',
      'fb_idea': '💡 सुझाव',
      'fb_voice_note': '🎙️ आवाज़ में फीडबैक रिकॉर्ड करें',
      'fb_text_hint': 'बताएं कि क्या बेहतर किया जा सकता है...',
      'fb_submit': 'प्रतिक्रिया भेजें',
      'fb_thank_you': 'धन्यवाद! आपकी राय से सभी को मदद मिलेगी।',
      'demo_badge': 'उदाहरण / डेमो कहानी',
      'demo_banner_title': 'प्रमाण कैसे काम करता है',
      'demo_banner_sub': 'वास्तविक बदलाव पहले और बाद के प्रमाण से साबित होता है।',
      'safety_title': '🛡️ विश्वास और सुरक्षा का वादा',
      'safety_desc': 'कोई भ्रामक दावा नहीं • वास्तविक प्रमाण सत्यापन • सुरक्षित इच्छा पूर्ति',
      'role_individual': 'व्यक्तिगत 👤',
      'role_group': 'सामुदायिक समूह 👥',
      'role_school': 'संस्थान / स्कूल 🏫',
      'role_ngo': 'एनजीओ / सामाजिक संस्था 🤝',
      'role_corporate': 'व्यवसाय / कॉर्पोरेट 🏢',
      'role_government': 'सरकार / नागरिक निकाय 🏛️',
    },
    'bn': {
      'nav_home': 'হোম',
      'nav_discover': 'আবিষ্কার',
      'nav_create': 'তৈরি করুন',
      'nav_wishes': 'ইচ্ছা',
      'nav_me': 'প্রোফাইল',
      'app_title': 'কর্ম গ্রিড',
      'app_tagline': 'ভালোর প্রমাণ',
      'app_hero_sub': 'ভালো কাজ করুন। পরিবর্তন দেখান। প্রভাব তৈরি করুন।',
      'login_title': 'আপনার কর্ম পাসপোর্ট খুলুন',
      'login_subtitle': 'গুগল দিয়ে সাইন ইন করুন এবং কর্ম অর্জন করুন',
      'login_google_btn': 'Google / Gmail দিয়ে এগিয়ে যান',
      'dash_welcome': 'স্বাগতম',
      'dash_karma': 'কর্ম',
      'dash_impact': 'প্রভাব',
      'dash_trust': 'আস্থা স্কোর',
      'dash_action_do': '🌱 ভালো কাজ',
      'dash_action_do_sub': 'কাজ খুঁজুন ও প্রমাণ দিন',
      'dash_action_report': '🔎 সমস্যা জানান',
      'dash_action_report_sub': 'এলাকার সমস্যা রিপোর্ট করুন',
      'dash_action_wish': '✨ ইচ্ছা প্রকাশ',
      'dash_action_wish_sub': 'সাহায্য চান',
      'dash_action_help_wish': '🤝 ইচ্ছা পূরণ',
      'dash_action_help_wish_sub': 'অন্যকে সাহায্য করুন',
      'dash_search_placeholder': '🔎 কাজ, সমস্যা, স্কুল বা ইচ্ছা খুঁজুন...',
      'dash_talk_mic': '🎙️ কর্মের সাথে কথা বলুন',
      'step_before': 'আগে 📸',
      'step_action': 'কাজ ⚡',
      'step_after': 'পরে 📸',
      'step_verified': 'যাচাইকৃত ✓',
      'step_impact': 'প্রভাব 🌍',
      'step_karma': 'কর্ম ✨',
      'fb_button': 'মতামত',
      'demo_badge': 'উদাহরণ / ডেমো গল্প',
      'safety_title': '🛡️ আস্থা ও সুরক্ষার নিশ্চয়তা',
    },
    'te': {
      'nav_home': 'హోమ్',
      'nav_discover': 'అన్వేషించండి',
      'nav_create': 'సృష్టించండి',
      'nav_wishes': 'కోరికలు',
      'nav_me': 'ప్రొఫైల్',
      'app_title': 'కర్మ గ్రిడ్',
      'app_tagline': 'మంచికి రుజువు',
      'app_hero_sub': 'మంచి చేయండి. మార్పును చూపండి. ప్రభావం చూపండి.',
      'login_title': 'మీ కర్మ పాస్‌పోర్ట్ తెరవండి',
      'login_subtitle': 'Google తో సైన్ ఇన్ చేసి కర్మ పొందండి',
      'login_google_btn': 'Google / Gmail తో కొనసాగండి',
      'dash_welcome': 'స్వాగతం',
      'dash_karma': 'కర్మ',
      'dash_impact': 'ప్రభావం',
      'dash_trust': 'నమ్మకం స్కోరు',
      'dash_action_do': '🌱 మంచి పని చేయండి',
      'dash_action_do_sub': 'పనిని ఎంచుకుని రుజువు చేయండి',
      'dash_action_report': '🔎 సమస్య నివేదించండి',
      'dash_action_report_sub': 'సమస్యను తెలియజేయండి',
      'dash_action_wish': '✨ కోరిక కోరండి',
      'dash_action_wish_sub': 'సహాయం అడగండి',
      'dash_action_help_wish': '🤝 సహాయం చేయండి',
      'dash_action_help_wish_sub': 'మరొకరికి అండగా నిలవండి',
      'dash_search_placeholder': '🔎 పనులు, సమస్యలు లేదా కోరికలను వెతకండి...',
      'dash_talk_mic': '🎙️ కర్మతో మాట్లాడండి',
      'step_before': 'ముందు 📸',
      'step_action': 'పని ⚡',
      'step_after': 'తరువాత 📸',
      'step_verified': 'ధృవీకరించబడింది ✓',
      'step_impact': 'ప్రభావం 🌍',
      'step_karma': 'కర్మ ✨',
      'fb_button': 'అభిప్రాయం',
      'demo_badge': 'ఉదాహరణ / డెమో కథ',
      'safety_title': '🛡️ నమ్మకం & భద్రత హామీ',
    },
    'ta': {
      'nav_home': 'முகப்பு',
      'nav_discover': 'கண்டுபிடி',
      'nav_create': 'உருவாக்கு',
      'nav_wishes': 'விருப்பங்கள்',
      'nav_me': 'சுயவிவரம்',
      'app_title': 'கர்மா கிரிட்',
      'app_tagline': 'நன்மையின் சான்று',
      'app_hero_sub': 'நன்மை செய்யுங்கள். மாற்றத்தை காட்டுங்கள். தாக்கத்தை உருவாக்குங்கள்.',
      'login_title': 'உங்கள் கர்மா பாஸ்போர்ட்டை திறக்கவும்',
      'login_subtitle': 'கூகிள் மூலம் உள்நுழைந்து கர்மா புள்ளிகளைப் பெறுங்கள்',
      'login_google_btn': 'Google / Gmail உடன் தொடரவும்',
      'dash_welcome': 'நல்வரவு',
      'dash_karma': 'கர்மா',
      'dash_impact': 'தாக்கம்',
      'dash_trust': 'நம்பிக்கை மதிப்பீடு',
      'dash_action_do': '🌱 நன்மை செய்',
      'dash_action_do_sub': 'ஒரு நற்செயலைச் செய்து சாட்சியளியுங்கள்',
      'dash_action_report': '🔎 புகாரளி',
      'dash_action_report_sub': 'உள்ளூர் பிரச்சனையைத் தெரிவிக்கவும்',
      'dash_action_wish': '✨ விருப்பம் கோரு',
      'dash_action_wish_sub': 'உதவி கேளுங்கள்',
      'dash_action_help_wish': '🤝 விருப்பத்திற்கு உதவு',
      'dash_action_help_wish_sub': 'மற்றவர்களுக்கு உதவுங்கள்',
      'dash_search_placeholder': '🔎 செயல்கள், பிரச்சனைகள் அல்லது விருப்பங்களைத் தேடுங்கள்...',
      'dash_talk_mic': '🎙️ கர்மாவுடன் பேசுங்கள்',
      'step_before': 'முன் 📸',
      'step_action': 'செயல் ⚡',
      'step_after': 'பின் 📸',
      'step_verified': 'சரிபார்க்கப்பட்டது ✓',
      'step_impact': 'தாக்கம் 🌍',
      'step_karma': 'கர்மா ✨',
      'fb_button': 'கருத்து',
      'demo_badge': 'எடுத்துக்காட்டு கதை',
      'safety_title': '🛡️ நம்பிக்கை மற்றும் பாதுகாப்பு',
    },
    'mr': {
      'nav_home': 'मुख्यपृष्ठ',
      'nav_discover': 'शोधा',
      'nav_create': 'तयार करा',
      'nav_wishes': 'इच्छा',
      'nav_me': 'माझे खाते',
      'app_title': 'कर्म ग्रिड',
      'app_tagline': 'चांगुलपणाचा पुरावा',
      'app_hero_sub': 'चांगले कार्य करा. बदल दाखवा. प्रभाव निर्माण करा.',
      'login_title': 'आपला कर्म पासपोर्ट उघडा',
      'login_subtitle': 'Google द्वारे साइन इन करा आणि कर्म मिळवा',
      'login_google_btn': 'Google / Gmail द्वारे सुरू ठेवा',
      'dash_welcome': 'स्वागत आहे',
      'dash_karma': 'कर्म',
      'dash_impact': 'प्रभाव',
      'dash_trust': 'विश्वास गुण',
      'dash_action_do': '🌱 चांगले कार्य',
      'dash_action_do_sub': 'कार्य निवडा आणि पुरावा द्या',
      'dash_action_report': '🔎 समस्या नोंदवा',
      'dash_action_report_sub': 'स्थानिक समस्येची तक्रार करा',
      'dash_action_wish': '✨ इच्छा व्यक्त करा',
      'dash_action_wish_sub': 'मदत मागा',
      'dash_action_help_wish': '🤝 इच्छेला मदत करा',
      'dash_action_help_wish_sub': 'दुसऱ्याला मदत करा',
      'dash_search_placeholder': '🔎 कार्ये, समस्या किंवा इच्छा शोधा...',
      'dash_talk_mic': '🎙️ कर्माशी बोला',
      'step_before': 'पूर्वी 📸',
      'step_action': 'कृती ⚡',
      'step_after': 'नंतर 📸',
      'step_verified': 'सत्यापित ✓',
      'step_impact': 'प्रभाव 🌍',
      'step_karma': 'कर्म ✨',
      'fb_button': 'अभिप्राय',
      'demo_badge': 'उदाहरण कथा',
      'safety_title': '🛡️ विश्वास व सुरक्षितता',
    },
    'ur': {
      'nav_home': 'ہوم',
      'nav_discover': 'دریافت',
      'nav_create': 'شامل کریں',
      'nav_wishes': 'خواہشات',
      'nav_me': 'پروفائل',
      'app_title': 'کرما گرڈ',
      'app_tagline': 'نیکی کا ثبوت',
      'app_hero_sub': 'نیکی کریں۔ فرق دکھائیں۔ اثر پیدا کریں۔',
      'login_title': 'اپنا کرما پاسپورٹ کھولیں',
      'login_subtitle': 'گوگل کے ساتھ سائن ان کریں اور کرما کمائیں',
      'login_google_btn': 'Google / Gmail کے ساتھ جاری رکھیں',
      'dash_welcome': 'خوش آمدید',
      'dash_karma': 'کرما',
      'dash_impact': 'اثر',
      'dash_trust': 'اعتماد کا سکور',
      'dash_action_do': '🌱 نیکی کریں',
      'dash_action_do_sub': 'نیک عمل منتخب کریں اور ثبوت دیں',
      'dash_action_report': '🔎 مسئلہ بتائیں',
      'dash_action_report_sub': 'کسی مقامی مسئلے کی اطلاع دیں',
      'dash_action_wish': '✨ خواہش بتائیں',
      'dash_action_wish_sub': 'کمیونٹی سے مدد لیں',
      'dash_action_help_wish': '🤝 خواہش پوری کریں',
      'dash_action_help_wish_sub': 'کسی کی مدد کریں',
      'dash_search_placeholder': '🔎 کام، مسائل یا خواہشات تلاش کریں...',
      'dash_talk_mic': '🎙️ کرما سے بات کریں',
      'step_before': 'پہلے 📸',
      'step_action': 'عمل ⚡',
      'step_after': 'بعد میں 📸',
      'step_verified': 'تصدیق شدہ ✓',
      'step_impact': 'اثر 🌍',
      'step_karma': 'کرما ✨',
      'fb_button': 'رائے',
      'demo_badge': 'مثالی کہانی',
      'safety_title': '🛡️ اعتماد اور تحفظ کا وعدہ',
    },
    'he': {
      'nav_home': 'בית',
      'nav_discover': 'גילוי',
      'nav_create': 'יצירה',
      'nav_wishes': 'משאלות',
      'nav_me': 'פרופיל',
      'app_title': 'קארמה גריד',
      'app_tagline': 'הוכחת הטוב',
      'app_hero_sub': 'עשה טוב. הראה את ההבדל. צור השפעה.',
      'login_title': 'גישה לדרכון הקארמה שלך',
      'login_subtitle': 'התחבר עם גוגל כדי להרוויח קארמה',
      'login_google_btn': 'המשך עם Google / Gmail',
      'dash_welcome': 'ברוך הבא',
      'dash_karma': 'קארמה',
      'dash_impact': 'השפעה',
      'dash_trust': 'ציון אמון',
      'dash_action_do': '🌱 עשה טוב',
      'dash_action_do_sub': 'בצע מעשה טוב והוכח השפעה',
      'dash_action_report': '🔎 דווח על בעיה',
      'dash_action_report_sub': 'דווח על בעיה מקומית לתיקון',
      'dash_action_wish': '✨ בקש משאלה',
      'dash_action_wish_sub': 'בקש עזרה מהקהילה',
      'dash_action_help_wish': '🤝 עזור למשאלה',
      'dash_action_help_wish_sub': 'תמוך במישהו שזקוק לעזרה',
      'dash_search_placeholder': '🔎 חפש פעולות, בעיות או משאלות...',
      'dash_talk_mic': '🎙️ דבר עם קארמה',
      'step_before': 'לפני 📸',
      'step_action': 'פעולה ⚡',
      'step_after': 'אחרי 📸',
      'step_verified': 'מאומת ✓',
      'step_impact': 'השפעה 🌍',
      'step_karma': 'קארמה ✨',
      'fb_button': 'משוב',
      'demo_badge': 'דוגמה / סיפור הדגמה',
      'safety_title': '🛡️ הבטחת אמון ובטיחות',
    },
    'ar': {
      'nav_home': 'الرئيسية',
      'nav_discover': 'استكشاف',
      'nav_create': 'إنشاء',
      'nav_wishes': 'الأمنيات',
      'nav_me': 'حسابي',
      'app_title': 'كارما جريد',
      'app_tagline': 'برهان الخير',
      'app_hero_sub': 'افعل الخير. أظهر الفرق. اصنع الأثر.',
      'login_title': 'الوصول إلى جواز كارما الخاص بك',
      'login_subtitle': 'سجل الدخول باستخدام جوجل لكسب كارما',
      'login_google_btn': 'المتابعة باستخدام Google / Gmail',
      'dash_welcome': 'أهلاً بك',
      'dash_karma': 'كارما',
      'dash_impact': 'الأثر',
      'dash_trust': 'معدل الثقة',
      'dash_action_do': '🌱 افعل الخير',
      'dash_action_do_sub': 'اختر عملاً صالحاً واثبت الأثر',
      'dash_action_report': '🔎 أبلغ عن مشكلة',
      'dash_action_report_sub': 'أبلغ عن مشكلة في منطقتك',
      'dash_action_wish': '✨ اطلب أمنية',
      'dash_action_wish_sub': 'اطلب مساعدة المجتمع',
      'dash_action_help_wish': '🤝 ساعد في أمنية',
      'dash_action_help_wish_sub': 'ادعم محتاجاً',
      'dash_search_placeholder': '🔎 ابحث عن أنشطة أو مشاكل أو أمنيات...',
      'dash_talk_mic': '🎙️ تحدث إلى كارما',
      'step_before': 'قبل 📸',
      'step_action': 'فعل ⚡',
      'step_after': 'بعد 📸',
      'step_verified': 'تم التحقق ✓',
      'step_impact': 'الأثر 🌍',
      'step_karma': 'كارما ✨',
      'fb_button': 'ملاحظات',
      'demo_badge': 'قصة تجريبية / مثال',
      'safety_title': '🛡️ ضمان الثقة والأمان',
    }
  };

  static String translate(String key, {String lang = 'en', String defaultValue = ''}) {
    final cleanLang = _normalizeLangCode(lang);
    if (_localizedValues.containsKey(cleanLang) && _localizedValues[cleanLang]!.containsKey(key)) {
      return _localizedValues[cleanLang]![key]!;
    }
    if (_localizedValues['en']!.containsKey(key)) {
      return _localizedValues['en']![key]!;
    }
    return defaultValue.isNotEmpty ? defaultValue : key;
  }

  static String translateWithContext(BuildContext context, String key, {String defaultValue = ''}) {
    try {
      final auth = Provider.of<AuthProvider>(context, listen: false);
      return translate(key, lang: auth.currentLanguage, defaultValue: defaultValue);
    } catch (_) {
      return translate(key, lang: 'en', defaultValue: defaultValue);
    }
  }

  static String _normalizeLangCode(String lang) {
    final lower = lang.toLowerCase().trim();
    for (final l in supportedLanguages) {
      if (l['code'] == lower || l['name']!.toLowerCase() == lower || l['native']!.toLowerCase() == lower) {
        return l['code']!;
      }
    }
    return 'en';
  }
}
